/**
 * Central configuration. Devnet only — see README.
 *
 * Nothing in here is a secret. Wallet seeds live in data/wallets.json, which is
 * gitignored and regenerated by `npm run provision`.
 */

export const NETWORK_URL =
  process.env.XRPL_NETWORK_URL ?? 'wss://s.devnet.rippletest.net:51233/';

export const FAUCET_URL =
  process.env.XRPL_FAUCET_URL ?? 'https://faucet.devnet.rippletest.net/accounts';

export const EXPLORER_BASE = process.env.XRPL_EXPLORER ?? 'https://devnet.xrpl.org';

/** Amendments this project depends on. IDs are derived, not hardcoded — see ledger/amendments.ts. */
export const REQUIRED_AMENDMENTS = ['SingleAssetVault', 'LendingProtocol'] as const;

/** The demo stablecoin. Issued by our own devnet `issuer` wallet. */
export const DEMO_CURRENCY = 'USD';

/**
 * Decimal places the vault tracks internally for its IOU asset.
 * XLS-65 lets an IOU vault declare a Scale (0–18); share MPTs are minted as
 * `assets * 10^Scale` into an integer MPT balance. 6 keeps share counts well
 * inside MPT's 64-bit range for fund sizes up to ~10^12 USD.
 */
export const VAULT_SCALE = 6;

/**
 * How the ledger interprets `InterestRate` on a Loan.
 *
 *   'per-period' — the rate applies once per PaymentInterval.
 *   'annual'     — the rate is annualised; the ledger prorates it by
 *                  PaymentInterval / seconds-in-a-year.
 *
 * VERIFIED EMPIRICALLY as 'annual' — see docs/verified.md. A loan originated with
 * InterestRate=1583, PaymentInterval=240, PaymentTotal=6 on principal 127500 came
 * back from the ledger with PeriodicPayment=21250.008960073992. That matches the
 * annualised-and-prorated hypothesis and is off by a factor of ~131,000 from the
 * per-period one, so this is not a close call.
 *
 * `npm run lifecycle` re-runs the probe on every execution and will say so if the
 * ledger ever changes its mind.
 */
export type InterestRateBasis = 'per-period' | 'annual';
export const INTEREST_RATE_BASIS: InterestRateBasis =
  (process.env.INTEREST_RATE_BASIS as InterestRateBasis) ?? 'annual';

/**
 * Seconds in a year, as the ledger counts them.
 *
 * VERIFIED EMPIRICALLY: solving the observed PeriodicPayment above for the implied
 * year length gives 365.244 days. That is the Julian year — 365.25 days — and
 * reproducing the ledger's figure with it lands within 9e-6 of a dollar on a
 * $127,500 loan. Neither 360 nor 365 fits.
 */
export const SECONDS_PER_YEAR = Math.round(365.25 * 24 * 60 * 60); // 31,557,600

/** Paths for the JSON persistence layer (D5: the ledger is the source of truth). */
export const DATA_DIR = 'data';
export const WALLETS_FILE = `${DATA_DIR}/wallets.json`;
export const STATE_FILE = `${DATA_DIR}/state.json`;
export const TXLOG_FILE = `${DATA_DIR}/txlog.json`;

export const explorerTx = (hash: string) => `${EXPLORER_BASE}/transactions/${hash}`;
export const explorerAccount = (address: string) => `${EXPLORER_BASE}/accounts/${address}`;
